version: "3.7"

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chore
    ports:
      - '5432:5432'
    volumes:
      - ./data/pg:/var/lib/postgresql/data
